### ISSUE TITLE
Loading local file doesn't do anything at all

### ISSUE THREAD

**Issue by Trophime** [Kitware/pv-web-viewer#27]
Hi,
I manage to get `pv-web-viewer` working within a singularity container
but I can't load any file into the "Paraview Glance"...
Actually I've tried with `sphere.vtk` from `vtk-js/Data/legacy\...`

Is this a bug?
If not, How shall I proceed to load local file?

Best
C

**Comment by jourdain** [comment]
The supported file format as standalone HTML is `*.vtp` and `*.vti`. The legacy VTK reader is not supported as its current implementation in vtk.js is fairly limited (polydata - no data).

Online, we leverage ITK for its reader as well but those can only produce vtkImageData. The `*.vtk` file format that you see is coming from ITK. So it won't handle the mesh properly like the sphere example file.

**Comment by Trophime** [comment]
Ok thanks.
To be clear it would be better to have only supported file format listed under `Load local file` menu.

**Comment by jourdain** [comment]
Everything listed is supported. But the `vtk` reader that is listed can only read files that encode `vtkImageData`, not `vtkUnstructuredGrid`, `vtkPolyData`, `vtkRectilinearGrid`, `vtkStructuredGrid`, `vtkTable`.

The legacy vtk file format has only one file extension for all the possible data type that he can encode.

Do you think we should remove it from the listing as it only handle one data format?

**Comment by Trophime** [comment]
I believe that only the extensions corresponding to the format that are supported should be listed.
It will help users.

**Comment by jourdain** [comment]
@thewtex Does ITK `*.vtk` reader can read geometry or just Volume data? If geometry is supported we should try to handle the data conversion to vtk.js.

**Comment by thewtex** [comment]
Currently it only supports volume data (geometry support will come in the future, though). We could try reading with vtk.js to handle the geometry data.
