### ISSUE TITLE
Adblockers (e.g. uBlock Origin) prevent reading ITK images

### ISSUE THREAD

**Issue by floryst** [Kitware/pv-web-viewer#62]
Adblockers that use the EasyPrivacy list block downloading of itk-js wasm files. On my uBlock Origin install, all wasm files from github.io are blocked.

This only happens on online-hosted glance: https://kitware.github.io/pv-web-viewer/nightly/ since it's hosted on a github.io page.

This should be detected by Glance and a popup should notify the user to disable Adblock for the website.

**Comment by agirault** [comment]
Also, can we catch the error instead of failing?
