### ISSUE TITLE
Volume slice visbility broken

### ISSUE THREAD

**Issue by floryst** [Kitware/pv-web-viewer#77]
Enabling slice visibility in volume view will freeze the volume view and output the following warning:

```
Error: WebGL warning: clear: Framebuffer not complete. (status: 0x8cd7) 
```

Isolated to this vtk-js commit: https://github.com/Kitware/vtk-js/commit/dec5008afc5298b52ed609abd38bec1d5a36a515

Haven't looked much into it yet, but @martinken do you recognize the warning?

**Comment by martinken** [comment]
Yes, that warning typically means someone is trying to use a framebuffer that is missing something it needs (such as a depth buffer or color buffer)

**Comment by martinken** [comment]
Should be fixed by https://github.com/Kitware/vtk-js/pull/733
